FROM dorowu/ubuntu-desktop-lxde-vnc:latest

RUN apt-get update && apt-get upgrade -y

# python 3.7
RUN apt-get install -y python3.7
RUN rm /usr/bin/python3
RUN ln -s /usr/bin/python3.7 /usr/bin/python3

RUN apt-get install -y python3-pip
RUN python3 -m pip install --upgrade pip

# DeepLabCut 2.2
RUN apt-get install -y \
    libwebkitgtk-3.0-dev \
    libgtk-3-dev \
    libsm-dev \
    freeglut3 \
    freeglut3-dev \
    libnotify-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    dpkg-dev \
    build-essential \
    libjpeg-dev \
    libtiff-dev \
    libsdl1.2-dev \
    software-properties-common
RUN pip3 install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.7.post2-cp37-cp37m-linux_x86_64.whl
RUN pip3 install 'deeplabcut[gui]'
RUN pip3 install ipywidgets
RUN pip3 install seaborn

# CUDA
COPY --from=nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04 /usr/local/cuda-11.0/ /usr/local/cuda-11.0
RUN ln -s /usr/local/cuda-11.0 /usr/local/cuda
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/cuda/lib:/usr/local/cuda/lib64
ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs:${LIBRARY_PATH}
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV NVIDIA_REQUIRE_CUDA "cuda>=11.0"

# language settings
RUN apt-get install -y locales
RUN locale-gen "en_US.UTF-8"
RUN locale-gen "en_GB.UTF-8"
RUN dpkg-reconfigure locales
